services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: lawrence
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    network_mode: bridge
    restart: unless-stopped